version: '3.9'

services:

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8083:8080
      - 50003:50000
    container_name: my-jenkins
    volumes:
      - ./data/jenkins_data:/var/jenkins_home

  db:
    container_name: mysql_db
    build:
      context: .
      dockerfile: db.Dockerfile
    environment:
      MYSQL_DATABASE: 'animated_eureka_database'
      MYSQL_PASSWORD: 'Destro333'
      MYSQL_ROOT_PASSWORD: 'Destro333'
    ports:
      - 3306:3306
    volumes:
      - animated_eureka_database:/var/lib/mysql

volumes:
  animated_eureka_database:
    external: false
