apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: mysql
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - name: tcp
      protocol: TCP
      port: 3306
      nodePort: 30471
